---
title: "readings"
author: "chloe"
date: "1/27/2021"
output: html_document
---

Wickham Excerpts
Hadley Wickham's textbook, Mastering Shiny, is a great text that walks you through Shiny development. Wickham goes into greater detail than is provided in the videos, though much of this should be review for you.

For now, read Part 1, Part 2, and Part 3.1-3.3. Work through every example and every code chunk.

These chapters provide two key pieces of information for you:

(1) Wickham provides an additional example of a "starter" Shiny app, with some additional comments that help to describe the general patterns in the structure of these apps

(2) Wickham provides an overview of some of the most common input and output functions

By the end of the reading and in conjunction with the videos, you should be comfortable building your own simple Shiny app from scratch.

I am intentionally not reviewing the concept of reactivity for this short course. Reactive programming is a somewhat more advanced concept than what is required when you are first learning Shiny. You may want to revisit this after you've mastered all the other skills we are working on.

https://mastering-shiny.org

The Shiny Tutorials
These are an extremely detailed set of walkthroughs and tutorials generated by RStudio about Shiny. These materials go into far more detail than the course videos, but if you want to take a very deep dive, they are a great resource. 

Going through all of these materials is unnecessary to grasp the skills needed for this course, but you should spend some time reviewing these materials now, and keep this in your pocket for future refreshing.

https://shiny.rstudio.com/tutorial/  


The Shiny Cheat Sheet
Like other Cheat Sheets we've seen, the Shiny cheat sheet provides a quick reference for many of the techniques we are working with. Right now, the Cheat Sheet has a lot more on it than what we've covered, but keep it in your back pocket.

https://shiny.rstudio.com/articles/cheatsheet.html  

At this point, I would focus on only the first page of the cheatsheet. The second page goes into greater detail that is necessary for the assignments in this course.

The Shiny Gallery
The Shiny Gallery has an exceptional set of examples of the kinds of applications you can build with Shiny, from very simple beginnings to very complex professional applications.

Additionally, you should note that, when you click on an example in the gallery, you'll see an option on the next page the "Get Code." This allows you to backwards engineer and use example code as a template for your own projects.

 Spend some time looking through these materials to get a sense of what Shiny can do!

https://shiny.rstudio.com/gallery/  


Deploying Apps to shinyapps.io
These articles from the  Shiny reference page provide a text-version of the instructions in the video for uploading apps to shinyapps.io. There isn't anything really different here from the videos, but if you want another set of step-by-step directions, this is a good backup.

https://shiny.rstudio.com/articles/deployment-web.html

https://shiny.rstudio.com/articles/shinyapps.html

Shiny Themes
The package shinythemes provides an easy way to apply some pre-baked design themes to your Shiny app. This is much like the ggthemes package, and the implementation is very easy to use.

Review this page to see how it is done, as well as a gallery for themes. Give it a try!

http://rstudio.github.io/shinythemes/?_ga=2.132961481.679985627.1601843315-1966566028.1601473074

Shiny Reference: Application Layout guide
This is an excellent, extremely clear write up about how to layout a Shiny app. We reviewed much of this in the video, but there are a few other options that you can learn about here. This is absolutely worth your time to review carefully.

https://shiny.rstudio.com/articles/layout-guide.html  

Make sure that you understand the following:

(1) Sidebar layout

(2) Tabsets

(3) Navlists

(4) Navbar pages

With these four options, you'll be able to complete the assignment for this week.

Intro to flexdashboard
This is the introduction provided for flexdashboard in the official documentation. It's review for you now, but available for you to check your understanding.

https://rmarkdown.rstudio.com/flexdashboard/index.html 

There are many parts of this page, but focus for now on the page where the link goes. Look at the different layout options and how they are created. We will fill in the gaps with material soon.

After you cover the layouts, you can look at the "Using" tab on the page. This is fairly comprehensive, coving layout, sizing, and also some additional advanced options. 

As you read, remember that you don't need all of this information to make a dashboard. These are all options for layouts. In this course, we are going to keep things fairly simple, so you can keep a narrow focus on the introductory material for right now.

Xie et al, Section 5.1
R Markdown: The Definitive Guide by Xie, Allaire, and Grolemund has a short section on flexdashboards. It's a useful additional resource. 

https://bookdown.org/yihui/rmarkdown/layout.html

Dashboard Layouts
The official documentation for flexdashboard has a great explainer on layout options. Some of this is covered in the lecture, and that will be enough to get you started. However, for a deeper explanation, reviewing the reference materials is necessary.

https://rmarkdown.rstudio.com/flexdashboard/layouts.html

Make sure that you understand these concepts:

(1) Fill vs. scroll vertical layout

(2) Tabsets

(3) Multiple pages

(4) Input sidebar layout

Shiny and flexdashboard
We cover the basics of integrating Shiny and flexdashboard in the video. Additional and advanced features are explained in the documentation:

https://rmarkdown.rstudio.com/flexdashboard/shiny.html  

Keep in mind that integrating Shiny and a flexdashboard is really not more complex than including Shiny in a R Markdown report. You only need to 4 things, which are laid out very clearly in the video and reading:

(1) Add runtime: shiny to the header at the top of the document

(2) Add {.sidebar} to the first column of dashboard. Put your input functions in this column.

(3) In the next column, add output by using render functions like renderPlot.

This will get you very far towards making a complete dashboard with Shiny integration. You have more options for advanced dashboards, but just getting this together is the foundation.